### PR TITLE
Added new Logo

### PR DESCRIPTION
**Pull request by piyush215j**
Added a new logo a modern logo nc Made by paint, some text, and with logopit free version

### CODE REVIEW

**Comment by ScorchingShade** [comment]
Loved the new logo, can you create some more assets with different sizes too? I will merge those pull requests!

**Comment by piyush215j** [comment]
yes bro i can no problem
please reply what you need and i will definitely help you out

**Comment by ScorchingShade** [comment]
Can you create logo png of different sizes? One possibly as a favicon?

**Comment by piyush215j** [comment]
please give me the sizes what you need
mention the different sizes what you need
i will definitely make it  as soon as possible

**Pull request merged**
